<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="HRWINLI3927" failures="1" tests="3" name="Test" time="62.346" errors="0" timestamp="25 Jan 2022 10:14:01 GMT">
  <testcase classname="com.hub.testcases.HUBLoginTests" name="loginTest" time="5.625">
    <failure type="java.lang.AssertionError" message="
expected: &amp;quot;HungerRush HUB | Dashboard&amp;quot;
 but was: &amp;quot;HungerRush HUB | LogOn&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
expected: "HungerRush HUB | Dashboard"
 but was: "HungerRush HUB | LogOn"
at com.hub.testcases.HUBLoginTests.loginTest(HUBLoginTests.java:28)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- loginTest -->
  <testcase classname="com.hub.testcases.HUBManageCouponTests" name="couponsPageTitle" time="37.734"/>
  <testcase classname="com.hub.testcases.HUBLoginTests" name="loginTest" time="51.211"/>
</testsuite> <!-- Test -->
